.\" Copyright (c) 2026 Joseph Koshy.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" $Id$
.\"
.Dd March 12, 2026
.Dt ELFTC_GET_PROGRAM_NAME 3
.Os
.Sh NAME
.Nm elftc_get_program_name
.Nd retrieve the name for the current program
.Sh LIBRARY
.Lb libelftc
.Sh SYNOPSIS
.In elftc_get_program_name.h
.Ft "const char *"
.Fn elftc_get_machine_name "void"
.Sh DESCRIPTION
Function
.Fn elftc_get_program_name
returns the name of the current program, if available.
If the name of the current program is unavailable, it returns a default
name instead.
.Sh RETURN VALUES
Function
.Fn elftc_get_program_name
returns a valid pointer to a
.Dv NUL Ns - Ns
terminated string.
.Sh ERRORS
Function
.Fn elftc_get_program_name
always succeeds.
.Sh SEE ALSO
.Xr getprogname 3 .
