# $Id$

TOP=		../../../..
SUBDIR=
SUBDIR+=	elftc_get_machine_name
SUBDIR+=	elftc_get_relocation_type_name
SUBDIR+=	elftc_string_table
SUBDIR+=	elftc_version

.include "${TOP}/mk/elftoolchain.subdir.mk"
